# Generated by Django 4.2.7 on 2023-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customer_adress_alter_customer_nid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Dob',
            field=models.DateField(default=''),
        ),
    ]
