# Generated by Django 4.2.7 on 2023-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
