# Generated by Django 4.2.7 on 2023-11-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customer_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('num_plate', models.CharField(max_length=7)),
                ('num_of_seat', models.IntegerField(default=0)),
                ('has_car', models.BooleanField(default=False)),
                ('Drivers_Nid', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Nid',
            new_name='Customer_Nid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_car',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car_listing')),
            ],
        ),
    ]
