# Generated by Django 4.2.7 on 2023-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_car_listing_driver_driving_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_listing',
            name='Driver_driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
