# Generated by Django 4.2.7 on 2023-11-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_car_listing_driver_driving_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_listing',
            name='has_car',
            field=models.CharField(max_length=7),
        ),
    ]
