# Generated by Django 4.2.7 on 2023-11-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_car_listing_has_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_listing',
            name='Driver_driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
