# Generated by Django 4.2.7 on 2023-11-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_car_listing_driver_driving_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_listing',
            name='Driver_driving_license',
        ),
    ]
