# Generated by Django 4.2.7 on 2023-11-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_car_listing_driver_driving_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Adress',
            new_name='Address',
        ),
    ]
