# Generated by Django 4.2.7 on 2023-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_adress_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_listing',
            name='Driver_driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
