# Generated by Django 4.2.7 on 2023-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_car_listing_driver_driving_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_listing',
            name='Car_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='car_listing',
            name='has_car',
            field=models.CharField(default='No', max_length=7),
        ),
    ]
