# Generated by Django 4.2.7 on 2023-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_car_listing_car_image_alter_car_listing_has_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_listing',
            name='Car_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
