# Generated by Django 4.2.7 on 2023-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_car_listing_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='customer_licence',
            field=models.ImageField(blank=True, null=True, upload_to='cimage/'),
        ),
    ]
