# Generated by Django 4.2.7 on 2023-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_car_customer_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='clocation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
