# Generated by Django 4.2.7 on 2023-12-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_customer_clocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='clocation',
        ),
        migrations.AddField(
            model_name='car_listing',
            name='clocation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
