# Generated by Django 4.2.7 on 2023-12-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
