# Generated by Django 5.0 on 2023-12-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_car_listing_cst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_listing',
            name='cst',
        ),
        migrations.RemoveField(
            model_name='car_listing',
            name='type_of_car',
        ),
    ]
