# Generated by Django 5.0 on 2023-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_car_listing_cst_car_listing_type_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_listing',
            name='type_of_car',
            field=models.CharField(choices=[('Private Car', 'Private Car'), ('Micro Bus', 'Micro Bus'), ('Mini bus', 'Mini bus')], default='', max_length=200),
        ),
    ]
