# Generated by Django 5.0 on 2023-12-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_car_listing_type_of_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_listing',
            name='has_car',
        ),
        migrations.AddField(
            model_name='car_listing',
            name='has_driver',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=7),
        ),
    ]
