# Generated by Django 5.0 on 2023-12-11 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='inf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
