# Generated by Django 4.2.7 on 2023-12-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
