# Generated by Django 4.2.7 on 2023-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_notification_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='car',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
