# Generated by Django 5.0 on 2023-12-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_listing',
            name='customer_licence',
        ),
        migrations.CreateModel(
            name='cs_driver_ifo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_licence', models.ImageField(blank=True, null=True, upload_to='cimage/')),
                ('cst2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
